AS
BEGIN
SET NOCOUNT ON;


	INSERT INTO DATA_TISSOT_EMAILS (MAIL,CREATED_DT,SOURCE,MAIL_DOMAIN)
	SELECT DISTINCT ADRESSE_EMAIL,DATE_CREATION,9,SUBSTRING(ADRESSE_EMAIL,CHARINDEX ('@',ADRESSE_EMAIL)+1,1000)
	FROM Tmp_Tissot_Ciam_Utilisateur
	WHERE NOT EXISTS (SELECT 1 FROM DATA_TISSOT_EMAILS WHERE DATA_TISSOT_EMAILS.MAIL = Tmp_Tissot_Ciam_Utilisateur.ADRESSE_EMAIL) AND OPTI_REJECTED=0
	AND
		(Tmp_Tissot_Ciam_Utilisateur.DATE_CREATION > DATEADD(YY,-2,getdate())
		OR
		Tmp_Tissot_Ciam_Utilisateur.DATE_DERNIER_LOGIN > DATEADD(YY,-2,getdate())
		OR
		Tmp_Tissot_Ciam_Utilisateur.DATE_DERNIERE_MAJ_PROFIL > DATEADD(YY,-2,getdate())
		);

	INSERT INTO USERS_TISSOT_EMAILS (MAIL,CREATED_DT,SUBSCRIBE_SOURCE,MAIL_DOMAIN,MAIL_CODE)
	SELECT DISTINCT ADRESSE_EMAIL,DATE_CREATION,9,SUBSTRING(ADRESSE_EMAIL,CHARINDEX ('@',ADRESSE_EMAIL)+1,1000),DATA_TISSOT_EMAILS.ID
	FROM Tmp_Tissot_Ciam_Utilisateur
	INNER JOIN DATA_TISSOT_EMAILS ON DATA_TISSOT_EMAILS.MAIL = Tmp_Tissot_Ciam_Utilisateur.ADRESSE_EMAIL
	WHERE NOT EXISTS (SELECT 1 FROM USERS_TISSOT_EMAILS WHERE USERS_TISSOT_EMAILS.MAIL = Tmp_Tissot_Ciam_Utilisateur.ADRESSE_EMAIL) AND OPTI_REJECTED=0
	AND
		(Tmp_Tissot_Ciam_Utilisateur.DATE_CREATION > DATEADD(YY,-2,getdate())
		OR
		Tmp_Tissot_Ciam_Utilisateur.DATE_DERNIER_LOGIN > DATEADD(YY,-2,getdate())
		OR
		Tmp_Tissot_Ciam_Utilisateur.DATE_DERNIERE_MAJ_PROFIL > DATEADD(YY,-2,getdate())
		);



MERGE DBO.USERS_TISSOT_LUMIO AS T
	USING (SELECT
            CIAM_ID AS NUM_CLIENT_CONTACT
            ,ADRESSE_EMAIL
            ,CIVILITE
            ,NOM
			,left(PRENOM,50) as PRENOM
            ,TEL_STANDARD
            ,MANDAT_REPRESENTATION
            ,EST_MANAGER
			,RAISON_SOCIALE_1
            ,CODE_APET
            ,EFFECTIF
            ,NUM_TELEPHONE
            ,USERS_TISSOT_EMAILS.MAIL_CODE AS MAIL_CODE
            ,SIRET
			,DATE_CREATION AS CREATED_DT
		FROM Tmp_Tissot_Ciam_Utilisateur
		INNER JOIN USERS_TISSOT_EMAILS WITH (NOlOCK) ON USERS_TISSOT_EMAILS.MAIL = Tmp_Tissot_Ciam_Utilisateur.ADRESSE_EMAIL
WHERE SIM_PARSELINE_RESULT = 1 AND OPTI_REJECTED=0
		) AS S
	ON (T.NUM_CLIENT_CONTACT COLLATE SQL_Latin1_General_CP1_CS_AS = S.NUM_CLIENT_CONTACT COLLATE SQL_Latin1_General_CP1_CS_AS)
	WHEN NOT MATCHED BY TARGET
		THEN
			INSERT(
            NUM_CLIENT_CONTACT
            ,MAIL
            ,CIVILITE
            ,NOM
            ,PRENOM
            ,PHONE_WORK
            ,MANDAT
            ,IS_MANAGER
            ,RAISON_SOCIALE1
            ,APE_CODE_NIV5
            ,TRANCHE_EFFECTIFS
            ,TEL_STANDARD
      	    ,MAIL_CODE
            ,SIRET
          ,CREATED_DT)
			VALUES(
           S.NUM_CLIENT_CONTACT
            ,S.ADRESSE_EMAIL
            ,S.CIVILITE
            ,S.NOM
	,S.PRENOM
            ,S.TEL_STANDARD
            ,S.MANDAT_REPRESENTATION
            ,S.EST_MANAGER
			,S.RAISON_SOCIALE_1
            ,S.CODE_APET
           ,S.EFFECTIF
           ,S.NUM_TELEPHONE
            ,S.MAIL_CODE
           ,S.SIRET
  	  ,S.CREATED_DT)
	WHEN MATCHED
		THEN
			UPDATE SET
             T.MAIL = S.ADRESSE_EMAIL
            ,T.CIVILITE = S.CIVILITE
            ,T.NOM = S.NOM
            ,T.PRENOM = S.PRENOM
            ,T.PHONE_WORK = S.TEL_STANDARD
            ,T.MANDAT = S.MANDAT_REPRESENTATION
            ,T.IS_MANAGER = S.EST_MANAGER
            ,T.RAISON_SOCIALE1 = S.RAISON_SOCIALE_1
            ,T.APE_CODE_NIV5 = S.CODE_APET
            ,T.TRANCHE_EFFECTIFS = S.EFFECTIF
            ,T.TEL_STANDARD = S.NUM_TELEPHONE
	    ,T.MAIL_CODE = S.MAIL_CODE
            ,T.SIRET = S.SIRET
            ,T.CREATED_DT = S.CREATED_DT
	    ,T.MODIFIED_DT=GETDATE();
END