-- etape 1 impossible de la mettre dans la SP Selligent
-- à mettre dans une autre SP qui se joue avant l'autre
 IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'ID_INFOCOLL' AND Object_ID = Object_ID(N'dbo.TMP_TI_VEILLE_PERSO_USER_TAG')) 
BEGIN 
	ALTER TABLE dbo.TMP_TI_VEILLE_PERSO_USER_TAG ADD ID_INFOCOLL VARCHAR(600) NULL;
END 
 IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'ID_ACTU' AND Object_ID = Object_ID(N'dbo.TMP_TI_VEILLE_PERSO_USER_TAG')) 
BEGIN 
	ALTER TABLE dbo.TMP_TI_VEILLE_PERSO_USER_TAG ADD ID_ACTU VARCHAR(600) NULL;
END 

-- etape 2
IF OBJECT_ID('TI_VAR_USER_INFOCOLL') IS NULL
CREATE TABLE TI_VAR_USER_INFOCOLL (UTILISATEUR VARCHAR(255),ID_INFOCOLL VARCHAR(65));

INSERT TI_VAR_USER_INFOCOLL (UTILISATEUR, ID_INFOCOLL)
SELECT TI_UT.UTILISATEUR,TI_I.ID
FROM TMP_TI_VEILLE_PERSO_USER_TAG AS TI_UT
CROSS APPLY STRING_SPLIT (TI_UT.ID_UNIQUE_INFOCOLL , ',' ) AS I
INNER JOIN ARTICLES_TI_CONTENU_INFOCOLL AS TI_I ON TI_I.ID_UNIQUE = I.VALUE;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes 
    WHERE object_id = OBJECT_ID('dbo.TI_VAR_USER_INFOCOLL')
    AND name='TI_VAR_USER_INFOCOLL_IDX')
CREATE INDEX TI_VAR_USER_INFOCOLL_IDX ON TI_VAR_USER_INFOCOLL (UTILISATEUR);

UPDATE TMP_TI_VEILLE_PERSO_USER_TAG
SET ID_UNIQUE_INFOCOLL =
(select DISTINCT
STUFF((Select ','+ID_INFOCOLL
from TI_VAR_USER_INFOCOLL T1
where ID_UNIQUE_INFOCOLL IS NOT NULL AND T1.UTILISATEUR=T2.UTILISATEUR
FOR XML PATH('')),1,1,'') from TI_VAR_USER_INFOCOLL T2 WHERE T2.UTILISATEUR = TMP_TI_VEILLE_PERSO_USER_TAG.UTILISATEUR);

DROP TABLE TI_VAR_USER_INFOCOLL;

-- etape 3
CREATE TABLE TI_VAR_USER_ACTU (UTILISATEUR VARCHAR(255),ID_ACTU VARCHAR(50));

INSERT TI_VAR_USER_ACTU(UTILISATEUR, ID_ACTU)
SELECT TI_UT.UTILISATEUR,TI_I.ID
FROM TMP_TI_VEILLE_PERSO_USER_TAG AS TI_UT
CROSS APPLY STRING_SPLIT (TI_UT.ID_UNIQUE_ACTU , ',' ) AS I
INNER JOIN ARTICLES_TI_CONTENU_EDITO AS TI_I ON TI_I.ID_UNIQUE = I.VALUE;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes 
    WHERE object_id = OBJECT_ID('dbo.TI_VAR_USER_ACTU')
    AND name='TI_VAR_USER_ACTU_IDX')
CREATE INDEX TI_VAR_USER_ACTU_IDX ON TI_VAR_USER_ACTU (UTILISATEUR);

UPDATE TMP_TI_VEILLE_PERSO_USER_TAG
SET ID_ACTU =
(select DISTINCT
STUFF((Select ','+ID_ACTU
from TI_VAR_USER_ACTU T1
where ID_UNIQUE_ACTU IS NOT NULL AND T1.UTILISATEUR=T2.UTILISATEUR
FOR XML PATH('')),1,1,'') from TI_VAR_USER_ACTU T2 WHERE T2.UTILISATEUR = TMP_TI_VEILLE_PERSO_USER_TAG.UTILISATEUR
AND ID_UNIQUE_ACTU IS NOT NULL);

DROP TABLE TI_VAR_USER_ACTU;

-- etape 4

INSERT ACTION_TI_VEILLE_PERSO (CREATED_DT, USERID, ACTIONCODE, INFOCOLL, ACTU, TAG )
SELECT GETDATE(),T2.ID,'VEILLE_PERSO',ID_INFOCOLL ,ID_ACTU ,TAG_LABEL 
FROM TMP_TI_VEILLE_PERSO_USER_TAG T1
INNER JOIN USERS_TI_EMAILS T2 with(nolock)  on T1.UTILISATEUR=T2.MAIL
and (ID_INFOCOLL is not null or ID_ACTU is not null);
