AS
BEGIN
SET NOCOUNT ON;


------------------------------------------------------------------ FLUX 74 THESAURUS -------------------------------------------------------------------------
TRUNCATE TABLE DATA_TI_THESAURUS;

INSERT INTO DATA_TI_THESAURUS (TAG_ID,TAG_LABEL)
SELECT TAG_ID,TAG_LABEL
FROM TMP_TI_THESAURUS;


------------------------------------------------------------------ FLUX 75 THESAURUS CONTENUS -----------------------------------------------------------------
TRUNCATE TABLE DATA_TI_THESAURUS_CONTENU;

INSERT INTO DATA_TI_THESAURUS_CONTENU (ID_ARTICLE,ORIGIN_ARTICLE,TAG_ID,ID_ARTICLE_SELLIGENT)
SELECT top 10
	TMP_TI_THESAURUS_CONTENT.ID_ARTICLE AS ID_ARTICLE,
	TMP_TI_THESAURUS_CONTENT.ORIGINE_ARTICLE AS ORIGIN_ARTICLE,
	TMP_TI_THESAURUS_CONTENT.TAG_ID AS TAG_ID,
	ARTICLES_TI_CONTENU_EDITO.ID AS ID_ARTICLE_SELLIGENT
FROM TMP_TI_THESAURUS_CONTENT
INNER JOIN ARTICLES_TI_CONTENU_EDITO ON TMP_TI_THESAURUS_CONTENT.ID_ARTICLE = ARTICLES_TI_CONTENU_EDITO.ID_ARTICLE
WHERE ORIGINE_ARTICLE=1;

INSERT INTO DATA_TI_THESAURUS_CONTENU (ID_ARTICLE,ORIGIN_ARTICLE,TAG_ID,ID_ARTICLE_SELLIGENT)
SELECT
	TMP_TI_THESAURUS_CONTENT.ID_ARTICLE AS ID_ARTICLE,
	TMP_TI_THESAURUS_CONTENT.ORIGINE_ARTICLE AS ORIGIN_ARTICLE,
	TMP_TI_THESAURUS_CONTENT.TAG_ID AS TAG_ID,
	ARTICLES_TI_CONTENU_INFOCOLL.ID AS ID_ARTICLE_SELLIGENT
FROM TMP_TI_THESAURUS_CONTENT
INNER JOIN ARTICLES_TI_CONTENU_INFOCOLL ON TMP_TI_THESAURUS_CONTENT.ID_ARTICLE = ARTICLES_TI_CONTENU_INFOCOLL.ID_ARTICLE
WHERE ORIGINE_ARTICLE=0;

------------------------------------------------------------------ FLUX 79 THESAURUS USERS---------------------------------------------------------------------------
IF (SELECT COUNT(*) FROM TMP_TI_THESAURUS_USER
WHERE OPTI_REJECTED = 0 AND SIM_PARSELINE_RESULT=1 )<> 0
BEGIN;

	TRUNCATE TABLE DATA_TI_THESAURUS_USERS;

	-- création des emails non existants
	INSERT INTO USERS_TI_EMAILS
	(MAIL,CREATED_DT,MAIL_DOMAIN)
	SELECT DISTINCT
		TMP_TI_THESAURUS_USER.email_adresse,
		GETDATE(),
		SUBSTRING(TMP_TI_THESAURUS_USER.email_adresse,CHARINDEX ('@',TMP_TI_THESAURUS_USER.email_adresse)+1,1000)
	FROM TMP_TI_THESAURUS_USER
	WHERE NOT EXISTS (SELECT 1 FROM USERS_TI_EMAILS WHERE MAIL = TMP_TI_THESAURUS_USER.email_adresse);


	-- insertion des correspondances emails/thesaurus
	INSERT INTO DATA_TI_THESAURUS_USERS (MAIL_CODE,TAG_ID)
	SELECT USERS_TI_EMAILS.ID, TAG_ID
	FROM TMP_TI_THESAURUS_USER
	INNER JOIN USERS_TI_EMAILS ON USERS_TI_EMAILS.MAIL = TMP_TI_THESAURUS_USER.email_adresse;

END;

------------------------------------------------------------------ FLUX 131 VEILLE PERSO---------------------------------------------------------------------------
INSERT INTO ARTICLES_TI_VEILLE_PERSO (ID,CREATED_DT,MODIFIED_DT,TITRE,LIEN,THEMATIQUE_LABEL,TAGS,MAIL_CODE,CONTENU,ACTU_INFOCOLL,TREATY_LABEL,ID_SELLIGENT_CONTENU,IMAGE,TYPE_ARTICLE,TYPE_CONTENU,DATE_CONTENU,AUTEUR,PDF_PRESENT,ID_ARTICLE,CONTENUS_A_ENVOYER,EDITOR_COMMENT_DATE,NOTE_EDITEUR)
SELECT ID,CREATED_DT,MODIFIED_DT,TITRE,LIEN,THEMATIQUE_LABEL,TAGS,MAIL_CODE,CONTENU,ACTU_INFOCOLL,TREATY_LABEL,ID_SELLIGENT_CONTENU,IMAGE,TYPE_ARTICLE,TYPE_CONTENU,DATE_CONTENU,AUTEUR,PDF_PRESENT,ID_ARTICLE,CONTENUS_A_ENVOYER,EDITOR_COMMENT_DATE,NOTE_EDITEUR
FROM TMP_ARTICLES_TI_VEILLE_PERSO;


------------------------------------------------------------------ FLUX 131 VEILLE PERSO---------------------------------------------------------------------------
INSERT INTO ARTICLES_TI_VEILLE_PERSO_TAGS (ID,CREATED_DT,MODIFIED_DT,MAIL_CODE,TAG_LABEL,DATE_CONTENU,CONTENUS_A_ENVOYER)
SELECT ID,CREATED_DT,MODIFIED_DT,MAIL_CODE,TAG_LABEL,DATE_CONTENU,CONTENUS_A_ENVOYER
FROM TMP_ARTICLES_TI_VEILLE_PERSO_TAGS;


END