SELECT COUNT(*) AS NB,'NB_USER_VEILLE_PERSO' AS STAT,''AS QUALIF 
FROM USERS_TI_EMAILS
WHERE EXISTS (SELECT 1 FROM DATA_TI_NL WHERE TITRE_CODE=699 AND STATUT_ABONNEMENT=1 AND USERS_TI_EMAILS.ID = DATA_TI_NL.MAIL_CODE)
UNION
--        Nb moyen de tag / abonné
SELECT COUNT(*)/COUNT(DISTINCT(MAIL_CODE)) AS NB,'NB_MOYEN_TAGS_USER' AS STAT,''AS QUALIF 
FROM DATA_TI_THESAURUS_USERS
WHERE NOT EXISTS (SELECT 1 FROM USERS_TI_EMAILS WHERE TESTUSER=1 AND USERS_TI_EMAILS.ID = DATA_TI_THESAURUS_USERS.MAIL_CODE)
UNION
--        Nb qui ont reçu une NL
SELECT COUNT(DISTINCT(MAIL_CODE)) AS NB,'NB_EMAIL_ENVOYE' AS STAT,''AS QUALIF 
FROM ARTICLES_TI_VEILLE_PERSO
WHERE CONTENUS_A_ENVOYER=1
--        Nb moyen d’élément par mail (total / ress doc / actu)
--Total : 
UNION
SELECT COUNT(*)/COUNT(DISTINCT(MAIL_CODE)) AS NB,'NB_ELEMENT_EMAIL' AS STAT ,''AS QUALIF
FROM ARTICLES_TI_VEILLE_PERSO
WHERE CONTENUS_A_ENVOYER=1

--Ressources docs
UNION
SELECT COUNT(*)/COUNT(DISTINCT(MAIL_CODE)) AS NB,'NB_ELEMENT_EMAIL_DOCS' AS STAT ,''AS QUALIF
FROM ARTICLES_TI_VEILLE_PERSO
WHERE CONTENUS_A_ENVOYER=1
AND ACTU_INFOCOLL=1

--Actu : 
UNION
SELECT COUNT(*)/COUNT(DISTINCT(MAIL_CODE)) AS NB,'NB_ELEMENT_EMAIL_ACTU' AS STAT ,''AS QUALIF
FROM ARTICLES_TI_VEILLE_PERSO
WHERE CONTENUS_A_ENVOYER=1
AND ACTU_INFOCOLL=0

---        Nb d’élément par mail (total / actu / ress doc) / compte (nb) d’email concerné


-- répartition nb emails par nb article infocoll
UNION
SELECT COUNT(DISTINCT(MAIL_CODE)) as NB,'REPARTITION_EMAIL_INFOCOLL' AS STAT,NB AS QUALIF FROM (SELECT MAIL_CODE,COUNT(*) AS NB
FROM ARTICLES_TI_VEILLE_PERSO
WHERE CONTENUS_A_ENVOYER=1
AND ACTU_INFOCOLL=1
GROUP BY MAIL_CODE) a
GROUP BY NB

-- répartition nb emails par nb article actu
UNION
SELECT COUNT(DISTINCT(MAIL_CODE)) as NB,'REPARTITION_EMAIL_ACTU' AS STAT,NB AS QUALIF FROM (SELECT MAIL_CODE,COUNT(*) AS NB
FROM ARTICLES_TI_VEILLE_PERSO
WHERE CONTENUS_A_ENVOYER=1
AND ACTU_INFOCOLL=0
GROUP BY MAIL_CODE) a
GROUP BY NB

-- réparition nb email par nb article tout confondu
UNION
SELECT COUNT(DISTINCT(MAIL_CODE)) as NB,'REPARTITION_EMAIL' AS STAT,NB AS QUALIF FROM (SELECT MAIL_CODE,COUNT(*) AS NB
FROM ARTICLES_TI_VEILLE_PERSO
WHERE CONTENUS_A_ENVOYER=1
GROUP BY MAIL_CODE) a
GROUP BY NB;