AS
BEGIN
SET NOCOUNT ON;

MERGE DBO.DATA_TISSOT_SUS_INFOSPEC AS T
	USING (SELECT TOP 100
	 USERS_TISSOT_SUSPECT.[ID] AS SUSPECT_ID,
				est_manager as IS_MANAGER,
				TACHES_PAIE as HAS_PAY_TASKS,
				taches_comptabilite as HAS_ACCOUNTING_TASKS,
				TACHES_RH as HAS_HR_TASKS,
				effectif AS SITE_EMPLOYEES,
				left(complement_adresse,50) AS ADDRESS_STREET1,
				left(adresse,50) AS ADDRESS_STREET2,
				left(complement_adresse,50) AS ADDRESS_STREET3,
				code_postal AS ADDRESS_POSTALCODE,
				left(ville,50) AS ADDRESS_CITY,
				f_pays AS ADDRESS_COUNTRY,
				f_service_tissot AS DEPARTMENT,
				mandat_representation AS MANDAT,
				f_fonction_tissot as TITLE,
				f_secteur_activite_tissot as ACTIVITY,
				CASE
					WHEN DATA_PP_DEPARTMENT.ID IS NOT NULL THEN DATA_PP_DEPARTMENT.ID
					ELSE 0
				END AS DEPARTMENT_CODE,
				CASE
					WHEN DATA_PP_TITLE.ID IS NOT NULL THEN DATA_PP_TITLE.ID
					ELSE 0
				END AS TITLE_CODE,
				CASE
					WHEN DATA_PM_ACTIVITY.ID IS NOT NULL THEN DATA_PM_ACTIVITY.ID
					ELSE 0
				END AS ACTIVITY_CODE
			FROM DBO.Tmp_Tissot_Ciam_Utilisateur
				INNER JOIN DBO.USERS_TISSOT_SUSPECT ON Tmp_Tissot_Ciam_Utilisateur.adresse_email = USERS_TISSOT_SUSPECT.MAIL
				LEFT JOIN DATA_PP_TITLE ON DATA_PP_TITLE.CODE = Tmp_Tissot_Ciam_Utilisateur.f_fonction_tissot
				LEFT JOIN DATA_PP_DEPARTMENT ON DATA_PP_DEPARTMENT.CODE = Tmp_Tissot_Ciam_Utilisateur.f_service_tissot
				LEFT JOIN DATA_PM_ACTIVITY ON DATA_PM_ACTIVITY.CODE = Tmp_Tissot_Ciam_Utilisateur.f_secteur_activite_tissot
				WHERE Tmp_Tissot_Ciam_Utilisateur.OPTI_REJECTED = 0 AND  SIM_PARSELINE_RESULT=1

				) AS S
	ON (T.SUSPECT_ID = S.SUSPECT_ID)
	WHEN NOT MATCHED BY TARGET
		THEN
			INSERT(
				SUSPECT_ID
				,IS_MANAGER
				,HAS_PAY_TASKS
				,HAS_ACCOUNTING_TASKS
				,HAS_HR_TASKS
				,SITE_EMPLOYEES
				,ADDRESS_STREET1
				,ADDRESS_STREET2
				,ADDRESS_STREET3
				,ADDRESS_POSTALCODE
				,ADDRESS_CITY
				,ADDRESS_COUNTRY
				,MANDAT
				,DEPARTMENT
				,TITLE
				,ACTIVITY
				,DEPARTMENT_CODE
				,TITLE_CODE
				,ACTIVITY_CODE)
			VALUES(
				S.SUSPECT_ID
				,S.IS_MANAGER
				,S.HAS_PAY_TASKS
				,S.HAS_ACCOUNTING_TASKS
				,S.HAS_HR_TASKS
				,S.SITE_EMPLOYEES
				,S.ADDRESS_STREET1
				,S.ADDRESS_STREET2
				,S.ADDRESS_STREET3
				,S.ADDRESS_POSTALCODE
				,S.ADDRESS_CITY
				,S.ADDRESS_COUNTRY
				,S.MANDAT
				,S.DEPARTMENT
				,S.TITLE
				,S.ACTIVITY
				,DEPARTMENT_CODE
				,TITLE_CODE
				,ACTIVITY_CODE)

	WHEN MATCHED
		THEN
			UPDATE SET
				T.IS_MANAGER = S.IS_MANAGER
				,T.HAS_PAY_TASKS = S.HAS_PAY_TASKS
				,T.HAS_ACCOUNTING_TASKS = S.HAS_ACCOUNTING_TASKS
				,T.HAS_HR_TASKS = S.HAS_HR_TASKS
				,T.SITE_EMPLOYEES = S.SITE_EMPLOYEES
				,T.ADDRESS_STREET1 = S.ADDRESS_STREET1
				,T.ADDRESS_STREET2 = S.ADDRESS_STREET2
				,T.ADDRESS_STREET3 = S.ADDRESS_STREET3
				,T.ADDRESS_POSTALCODE = S.ADDRESS_POSTALCODE
				,T.ADDRESS_CITY = S.ADDRESS_CITY
				,T.ADDRESS_COUNTRY = S.ADDRESS_COUNTRY
				,T.MANDAT = S.MANDAT
				,T.DEPARTMENT = S.DEPARTMENT
				,T.TITLE = S.TITLE
				,T.ACTIVITY = S.ACTIVITY
				,T.DEPARTMENT_CODE=S.DEPARTMENT_CODE
				,T.TITLE_CODE=S.TITLE_CODE
				,T.ACTIVITY_CODE=S.ACTIVITY_CODE;

END